vegaprotocol/vegawallet

- wallet/handler.go
- wallet/handler_test.go
- wallet/mocks/node_forward_mock.go
- wallet/mocks/wallet_handler_mock.go
- wallet/service.go
- wallet/service_test.go
Add a new endpoint to sign any payload not just a transacton.
> add endpoint to sign abitrary data

- cmd/run_dump_startup.go
- go.mod
- go.sum
- wallet/handler.go
- wallet/handler_test.go
- wallet/mocks/node_forward_mock.go
- wallet/mocks/wallet_handler_mock.go
- wallet/node_forward.go
- wallet/service.go
- wallet/service_test.go
- wallet/signed_bundle.go
This release PR bumps Vega API to v0.34.0 and updates import paths.
> Release v0.6.5

- cmd/run_dump_startup.go
- wallet/mocks/node_forward_mock.go
- wallet/node_forward.go
- wallet/service.go
- Make the healthcheck more useful.
- fix some of the endpoint docs printed at startup.
closes #79 
closes #78 
closes #73
> Few small fixes

- wallet/service.go
> Return if error happen on Health method

- wallet/node_forward.go
- wallet/service.go
This PR just add better logs for error when the transaction forwarded to the node end up returningt errors, + default sending transaction with SYNC.
> log and return better errors from the nodes

- crypto/hash.go
- service/mocks/wallet_handler_mock.go
- service/service.go
- service/service_deprecated.go
- service/service_test.go
- wallet/handler.go
> Add verify endpoint

- cmd/run_dump_startup.go
> Add command/* into the startup dump docs

- GETTING_STARTED.md
- README.md
- cmd/README.md
> Reorganise the readme to reincorporate starter instructions 

- cmd/service_run.go
- service/service.go
- service/service_test.go
This PR adds a REST API endpoint that returns app version info.
Closes #115
> Add endpoint that returns app version info (#115)

- commands/proposal_submission.go
- commands/proposal_submission_test.go
> Update proposalSubmission validation to be >= 0

- cmd/import.go
- cmd/key_generate.go
- cmd/key_list.go
- cmd/key_meta.go
- cmd/key_taint.go
- cmd/root.go
- cmd/service_init.go
- cmd/service_run.go
- cmd/sign.go
- cmd/verify.go
> Initialise store before handler in CLI

- GETTING_STARTED.md
- README.md
- cmd/README.md
- cmd/import.go
- cmd/init.go
- cmd/key_generate.go
- cmd/key_list.go
- cmd/key_meta.go
- cmd/key_taint.go
- cmd/root.go
- cmd/service_init.go
- cmd/service_run.go
- cmd/sign.go
- cmd/verify.go
- config/config.go
- config/config_test.go
This deprecates the `service init` command.
Close #123
Close #142
> Introduce an `init` command (#123 #142)

- README.md
> Update readme to link to master for instructions

- cmd/root.go
> Add short flag `-r` for root-path

- go.mod
- go.sum
- service/store/v1/store.go
- service/store/v1/store_helper_for_test.go
- service/store/v1/store_test.go
- wallet/store/v1/store.go
- wallet/store/v1/store_test.go
> Restrict file access

- cmd/init.go
- cmd/service_run.go
- logger/logger.go
> Configure logger level based on the config (#150)

- cmd/key_generate.go
- service/mocks/wallet_handler_mock.go
- service/service.go
- service/service_test.go
- wallet/handler.go
- wallet/handler_deprecated_test.go
- wallet/handler_test.go
- wallet/hd_wallet.go
- wallet/hd_wallet_test.go
- wallet/legacy_wallet.go
- wallet/store/v1/store_test.go
> Add default name to generated keys

- cmd/import.go
- cmd/key_generate.go
- cmd/key_list.go
- cmd/key_meta.go
- cmd/key_taint.go
- cmd/root.go
- cmd/sign.go
- cmd/verify.go
> Allow loading password from file (#143)

- GETTING_STARTED.md
- cmd/import.go
- cmd/key_generate.go
- cmd/key_list.go
- cmd/key_meta.go
- cmd/key_taint.go
- cmd/sign.go
- cmd/verify.go
> Remove short flag for passphrase

- .github/workflows/docker.yml
- Dockerfile
This PR adds a docker image build to CI.
Closes #171 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
> CI: Build docker image (#171)

- Dockerfile
- cmd/root.go
- cmd/service_run.go
- cmd/version.go
- console/console.go
- makefile
- service/service.go
- service/service_test.go
- version/version.go
> Expose Console service ouside of the command line

- wallet/handler.go
- wallet/hd_wallet.go
- wallet/legacy_wallet.go
Link to vegaprotocol/vega#3872
> Allow update of the wallet name

- go.mod
- go.sum
This PR bumps protos.
for vegaprotocol/vega#3857
> Bump protos

- Dockerfile
- cmd/list.go
- cmd/root.go
- libs/fs/fsutil.go
- libs/json/json.go
- service/store/v1/store.go
- wallet/handler.go
- wallet/mocked_store_for_test.go
- wallet/store/v1/store.go
- wallet/store/v1/store_test.go
> Add command to list all registered wallets

- cmd/README.md
> Document list subcommand

- cmd/README.md
- cmd/key_untaint.go
- wallet/errors.go
- wallet/handler.go
- wallet/hd_key_pair.go
- wallet/hd_key_pair_test.go
- wallet/hd_wallet.go
- wallet/hd_wallet_test.go
- wallet/legacy_wallet.go
- wallet/legacy_wallet_test.go
> Make untainting a key possible

- cmd/init.go
- service/config.go
- service/config_test.go
> Remove logger from service.GenerateConfig

- cmd/README.md
> Remove extra "it"

- cmd/import.go
- cmd/key_annotate.go
- cmd/key_generate.go
- cmd/key_list.go
- cmd/key_taint.go
- cmd/key_untaint.go
- cmd/root.go
- cmd/sign.go
- cmd/verify.go
- libs/fs/fs.go
- service/auth.go
- service/config.go
- service/mocks/store_mock.go
- service/rsa.go
- service/store/v1/store.go
- service/store/v1/store_test.go
- wallet/hd_wallet.go
- wallet/store/v1/store.go
> Improve service store API to get file information

- cmd/key_annotate.go
- cmd/root.go
> Add flag to clear metadata

- cmd/README.md
- cmd/import.go
- cmd/root.go
> Replace `--mnemonic` flag by `--mnemonic-path`

- go.mod
- go.sum
> Update protos dep

- go.mod
- go.sum
- wallet/commands.go
Fix the API checks on Delegate / Undelegate submissions
> fix wallet check

- cmd/service_run_startup.go
> Clean up the printed service endoint list

- cmd/init.go
- cmd/key_generate.go
> Add path of generated files on JSON output on init command

- cmd/README.md
- cmd/import.go
- cmd/init.go
- cmd/key_annotate.go
- cmd/key_generate.go
- cmd/key_list.go
- cmd/key_taint.go
- cmd/key_untaint.go
- cmd/list.go
- cmd/print.go
- cmd/root.go
- cmd/service_run.go
- cmd/service_run_startup.go
- cmd/sign.go
- cmd/verify.go
- service/node_forward.go
- service/service.go
- service/store/v1/store_test.go
- version/version.go
- wallet/hd_wallet_test.go
- wallet/store/v1/store.go
- wallet/store/v1/store_test.go
- wallets/store.go
Close #231 
- Migrate wallets store to XDG file structure
- Clean up some code
> Migrate wallets to XDG structure

- cmd/command.go
- wallet/handler.go
Implement the command subcommand in the go-wallet.
> add command subcommand to the wallet.

- cmd/command.go
- go.mod
- go.sum
- node/forwarder.go
- service/mocks/node_forward_mock.go
- service/service.go
- service/service_test.go
> SubmitTransactionV2 -> SubmitTransaction

- README.md
> Update getting started link to go to docs site

- README.md
> Readme copy change

- README.md
> Fix binaries section of README

- CHANGELOG.md
- cmd/printer/interactive.go
- cmd/root.go
- network/handler_test.go
> Ensure the interactive printer is listening to color management env var

- CHANGELOG.md
- cmd/flags/output.go
> Rename 'human' output to 'interactive'

- .github/workflows/changelog-checker.yml
- CHANGELOG.md
Add the changelog-checker.yml github action to ensure that the changelog is kept up-to-date
closes #363
> Add changelog checker Github action

- .github/workflows/changelog-checker.yml
- CHANGELOG.md
Update the changelog checker action to run only when needed
closes #365
> Update the changelog checker action

- CHANGELOG.md
- cmd/printer/interactive.go
- cmd/printer/interactive_unix.go
- cmd/printer/interactive_windows.go
> Attempt to enable ANSI colors in windows terminal

- CHANGELOG.md
- cmd/command.go
- cmd/flags/errors.go
- cmd/root.go
- cmd/send.go
- cmd/send_command.go
- cmd/send_command_test.go
- cmd/send_tx.go
- cmd/send_tx_test.go
> Introduce `send tx` subcommand

- CHANGELOG.md
- tests/sc_rename_wallet_test.go
- wallet/hd_wallet.go
- wallet/hd_wallet_test.go
- wallet/store/v1/store.go
> Remove wallet name serialisation

- CHANGELOG.md
- cmd/key_generate.go
- tests/commands_for_test.go
- tests/sc_annotate_key_test.go
- tests/sc_create_wallet_test.go
- tests/sc_describe_key_test.go
- tests/sc_generate_keys_test.go
- tests/sc_import_wallet_test.go
- tests/sc_isolate_wallet_test.go
- tests/sc_list_keys_test.go
- tests/sc_rename_wallet_test.go
- tests/sc_sign_and_verify_message_test.go
- tests/sc_taint_key_test.go
- wallet/handler.go
> Add wallet version to `key generate` output

- .github/workflows/add_issue_new_projects.yml
- .github/workflows/pr_verify_linked_issue.yml
- CHANGELOG.md
> Add new project board Github action and update linked PR action version

- CHANGELOG.md
- cmd/flags/force.go
- cmd/root.go
- cmd/wallet_delete.go
- cmd/wallet_delete_test.go
- tests/commands_for_test.go
- tests/sc_delete_wallet_test.go
- tests/sc_list_wallets_test.go
- wallet/store/v1/store.go
> Add command to remove a wallet

- CHANGELOG.md
- cmd/command_send.go
- cmd/key_rotate.go
- cmd/tx_send.go
- node/forwarder.go
> Fix `command send` examples

- CHANGELOG.md
- cmd/key_generate.go
> Update the important section of key generate

- CHANGELOG.md
- go.mod
- go.sum
- wallet/handler.go
- wallet/handler_test.go
- wallet/hd_public_key.go
- wallet/wallet.go
> Use new public key instead of hash & remove time

- CHANGELOG.md
- cmd/service_run.go
- service/handler.go
> Verify the service init state before trying to run it

- CHANGELOG.md
- cmd/README.md
- cmd/command_send.go
- cmd/init.go
- cmd/init_test.go
- cmd/key_annotate.go
- cmd/root.go
- cmd/tx_send.go
- cmd/version.go
- cmd/wallet_create.go
- cmd/wallet_delete.go
- cmd/wallet_import.go
> Improve help texts

- version/version.go
Set new ongoing version of the vega wallett.
> Set ongoing version

- .github/workflows/add-issue-to-team-board.yml
- .github/workflows/add-issues-to-sprint-board.yml
- .github/workflows/build-binaries.yml
- .github/workflows/build-docker-image.yml
- .github/workflows/label-issues.yml
- .github/workflows/release-binaries.yml
- .github/workflows/search-for-code-offences.yml
- .github/workflows/verify-changelog-is-updated.yml
- .github/workflows/verify-pr-has-linked-issue.yml
- CHANGELOG.md
- cmd/command.go
- cmd/command_send_test.go
- cmd/command_sign.go
- cmd/command_sign_test.go
- cmd/key_rotate.go
- cmd/tx_send_test.go
- tests/commands_for_test.go
- tests/sc_sign_and_verify_command_test.go
- wallet/handler.go
- wallet/handler_test.go
> Support signing commands offline

- CHANGELOG.md
- cmd/flags/force.go
> Fix confirmation prompt on windows

- CHANGELOG.md
- cmd/flags/passphrase.go
> Fail gracefully if trying to read password in msys

- CHANGELOG.md
- cmd/network.go
- cmd/network_locate.go
- tests/commands_for_test.go
- tests/helpers_for_test.go
- tests/sc_locate_networks_test.go
> Support locating the network config files fro CLI

- CHANGELOG.md
- cmd/message.go
- cmd/message_sign.go
- cmd/message_verify.go
- cmd/root.go
- tests/commands_for_test.go
> Move sign and verify to a message subcommand

- CHANGELOG.md
- cmd/cmd.go
- cmd/service_run.go
- cmd/tx.go
- network/network.go
- network/network_test.go
> Verify network configuration prior exploitation

- .github/workflows/release-binaries.yml
- CHANGELOG.md
> Sign windows binaries

- CHANGELOG.md
- cmd/version.go
> Insist on the fact that `vegawallet version` is not about the user wallet version

- .github/workflows/release-binaries.yml
- CHANGELOG.md
> Notarize MacOS application

- go.mod
- go.sum
Update the proto to get the latestest changes
> update to latest protos

- CHANGELOG.md
- go.mod
- go.sum
> Update protos to support internal time-triggered trading expiry

- .github/workflows/release-binaries.yml
> Add hard-coded version verification in release job

- go.mod
- go.sum
To help with vegaprotocol/vegawallet-desktop#56
> Update shared library for better errors

- .github/workflows/release-binaries.yml
- CHANGELOG.md
Downgraded Windows VM version so that the code signer will still work.
Closes #479
> Changed windows VM version

- CHANGELOG.md
- service/service.go
> Return tx in /api/v1/command response

- CHANGELOG.md
- commands/commands.go
> fix: unwrap transfer / cancel transfer properly

- CHANGELOG.md
- go.mod
- go.sum
Update the proto deps which will fix validation of the wallet.
close #521
> fix: update deps to get last update from the protos/command validations

- CHANGELOG.md
- README.md
Closes #520
Updates README to direct people to the desktop wallet app, and updates docs links to go to the new docs site.
> Add desktop wallet link, update docs links

- cmd/logger.go
- cmd/service_run.go
> Ensure the log file are using the --home flag

- .github/workflows/search-for-code-offences.yml
- .golangci.toml
- CHANGELOG.md
- service/policies.go
- service/service.go
> Add consent request received at time

- CHANGELOG.md
- cmd/tx_send.go
- go.sum
- service/mocks/policies_mock.go
- service/policies.go
- service/service.go
> feat: now displaying transaction hash after sending

- CHANGELOG.md
- Jenkinsfile
Make Vegacapsule ST required
Related PRs:
- https://github.com/vegaprotocol/data-node/pull/544
- https://github.com/vegaprotocol/system-tests/pull/737
- https://github.com/vegaprotocol/vega/pull/5308
- https://github.com/vegaprotocol/vegawallet/pull/551
> feat: add vegacapsule system tests

- CHANGELOG.md
- cmd/service_run.go
- cmd/tx_send.go
- service/mocks/policies_mock.go
- service/policies.go
- service/service.go
- service/service_test.go
> Printer utility shouldn't write in service response

- Jenkinsfile
Related PRs:
- https://github.com/vegaprotocol/vegawallet/pull/559
- https://github.com/vegaprotocol/vega/pull/5336
- https://github.com/vegaprotocol/system-tests/pull/765
- https://github.com/vegaprotocol/data-node/pull/593
> feat: remove dv system-tests

- CHANGELOG.md
- Jenkinsfile
- cmd/service_run.go
- cmd/tx_send.go
- go.mod
- go.sum
- node/forwarder.go
- service/mocks/node_forward_mock.go
- service/mocks/policies_mock.go
- service/mocks/wallet_handler_mock.go
- service/policies.go
- service/service.go
- service/service_test.go
- version/version.go
> Release version 0.15.0

- cmd/service_run.go
- service/errors.go
- service/mocks/policies_mock.go
- service/policies.go
- service/policies_test.go
- service/service.go
- service/service_test.go
> Make consent request cancelable

- CHANGELOG.md
- cmd/logger.go
- cmd/logger_unix.go
- cmd/logger_windows.go
> Ensure the winfile scheme for logger is register only once

- CHANGELOG.md
- README.md
- go.mod
- go.sum
- version/version.go
> Release version 0.16.0
